package net.MrGise.mmm.screen.bowyery_table;

import net.MrGise.mmm.recipe.BowyeryRecipe;
import net.MrGise.mmm.registry.content.ModBlocks;
import net.MrGise.mmm.registry.variables.ModMenuTypes;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.world.Container;
import net.minecraft.world.SimpleContainer;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.*;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;

import java.util.Optional;

public class BowyeryTableMenu extends AbstractContainerMenu {

    private final ContainerLevelAccess access;
    private final CraftingContainer craftSlots = new TransientCraftingContainer(this, 3, 1);
    private final ResultContainer resultSlots = new ResultContainer();
    private final Level level;

    private static final int BOW_INPUT_SLOT = 0;
    private static final int INGREDIENT_INPUT_SLOT_1 = 1;
    private static final int INGREDIENT_INPUT_SLOT_2 = 2;
    private static final int OUTPUT_SLOT = 3;

    public BowyeryTableMenu(int containerId, Inventory inv, FriendlyByteBuf extraData) {
        this(containerId, inv, ContainerLevelAccess.create(inv.player.level(), extraData.readBlockPos()));
    }

    public BowyeryTableMenu(int containerId, Inventory inv, ContainerLevelAccess access) {
        super(ModMenuTypes.BOWYERY_TABLE_MENU.get(), containerId);

        this.access = access;
        this.level = inv.player.level();
        Player player = inv.player;

        this.addSlot(new Slot(craftSlots, BOW_INPUT_SLOT, 26, 26));
        this.addSlot(new Slot(craftSlots, INGREDIENT_INPUT_SLOT_1, 39, 55));
        this.addSlot(new Slot(craftSlots, INGREDIENT_INPUT_SLOT_2, 57, 30));

        this.addSlot(new Slot(resultSlots, 0, 116, 26) {
            @Override
            public boolean mayPlace(ItemStack stack) {
                return false;
            }

            @Override
            public void onTake(Player player, ItemStack stack) {
                super.onTake(player, stack);

                // consume ingredients
                craftSlots.removeItem(BOW_INPUT_SLOT, 1);
                craftSlots.removeItem(INGREDIENT_INPUT_SLOT_1, 1);
                craftSlots.removeItem(INGREDIENT_INPUT_SLOT_2, 1);

                // recalculate recipe result
                slotsChanged(craftSlots);
            }
        });

        addPlayerInventory(inv);
        addPlayerHotbar(inv);
    }

    @Override
    public void slotsChanged(Container container) {
        if (!level.isClientSide) {
            ItemStack result = ItemStack.EMPTY;

            SimpleContainer inventory = new SimpleContainer(3);

            inventory.setItem(BOW_INPUT_SLOT, container.getItem(BOW_INPUT_SLOT).copy());
            inventory.setItem(INGREDIENT_INPUT_SLOT_1, container.getItem(INGREDIENT_INPUT_SLOT_1).copy());
            inventory.setItem(INGREDIENT_INPUT_SLOT_2, container.getItem(INGREDIENT_INPUT_SLOT_2).copy());

            Optional<BowyeryRecipe> recipe =
                    level.getRecipeManager().getRecipeFor(BowyeryRecipe.Type.INSTANCE, inventory, level);

            if (recipe.isPresent()) {
                result = recipe.get().assemble(inventory, level.registryAccess());
            }

            resultSlots.setItem(0, result);
            broadcastChanges();
        }
    }

    @Override
    public void removed(Player player) {
        super.removed(player);
        this.access.execute((level, pos) -> {
            this.clearContainer(player, craftSlots);
        });
    }

    // Generated by ChatGPT, sadly
    private static final int INPUT_SLOT_COUNT = 3;
    private static final int RESULT_SLOT_INDEX = 3;

    private static final int PLAYER_INV_START = 4;
    private static final int PLAYER_INV_END = 31;

    private static final int HOTBAR_START = 31;
    private static final int HOTBAR_END = 40;

    @Override
    public ItemStack quickMoveStack(Player player, int index) {
        Slot slot = this.slots.get(index);
        if (!slot.hasItem()) return ItemStack.EMPTY;

        ItemStack stack = slot.getItem();
        ItemStack copy = stack.copy();

        // Result slot → player inventory
        if (index == RESULT_SLOT_INDEX) {
            if (!moveItemStackTo(stack, PLAYER_INV_START, HOTBAR_END, true)) {
                return ItemStack.EMPTY;
            }
            slot.onQuickCraft(stack, copy);
        }

        // Player inventory → input slots
        else if (index >= PLAYER_INV_START) {
            if (!moveItemStackTo(stack, 0, INPUT_SLOT_COUNT, false)) {
                return ItemStack.EMPTY;
            }
        }

        // Input slots → player inventory
        else if (index < INPUT_SLOT_COUNT) {
            if (!moveItemStackTo(stack, PLAYER_INV_START, HOTBAR_END, false)) {
                return ItemStack.EMPTY;
            }
        }

        if (stack.isEmpty()) {
            slot.set(ItemStack.EMPTY);
        } else {
            slot.setChanged();
        }

        slot.onTake(player, stack);
        return copy;
    }

    private void addPlayerInventory(Inventory playerInventory) {
        for (int i = 0; i < 3; ++i) {
            for (int l = 0; l < 9; ++l) {
                this.addSlot(new Slot(playerInventory, l + i * 9 + 9, 8 + l * 18, 84 + i * 18));
            }
        }
    }

    private void addPlayerHotbar(Inventory playerInventory) {
        for (int i = 0; i < 9; ++i) {
            this.addSlot(new Slot(playerInventory, i, 8 + i * 18, 142));
        }
    }

    @Override
    public boolean stillValid(Player player) {
        return stillValid(access, player, ModBlocks.BOWYERY_TABLE.get());
    }
}
